### ISSUE TITLE
JSON api response varies

### ISSUE THREAD

**Issue by Viranchee** [gdgmad/gdgmadevents#22]
When I hit refresh, the JSON changes:
first fields for various refresh states:
venue, date, desc

**Comment by nikhil-thakkar** [comment]
Do you mean the order changes or value itself?

**Comment by Viranchee** [comment]
Hi Nikhil, the order changes

**Comment by nikhil-thakkar** [comment]
@Viranchee JSON object is a glorified dictionary and hence the order doesn't matter as long you reference the correct key.
