### ISSUE TITLE
License File

### ISSUE THREAD

**Issue by Viranchee** [gdgmad/gdgmadevents#5]
The license is yet to be added. What would the license be? MIT or GNU GPLv3?

**Comment by AniketSK** [comment]
@nikhil-thakkar @karntrehan what do you think of this?

**Comment by karntrehan** [comment]
Could be an MIT licence: https://en.wikipedia.org/wiki/MIT_License

**Comment by AniketSK** [comment]
I think @nikhil-thakkar would agree. @Viranchee could you fork, follow [this](https://stackoverflow.com/a/37895659/6877096) method (or any that you prefer) to add an MIT license, and send a PR?
Thanks for the very valuable suggestion. Let's get this done :)

**Comment by nikhil-thakkar** [comment]
Yup. MIT would work.

**Comment by Viranchee** [comment]
Yeah sure, apologies for the delay, saw the notification now

**Comment by nikhil-thakkar** [comment]
Done. Closing this.
