### ISSUE TITLE
Add more info about Lets build

### ISSUE THREAD

**Issue by karntrehan** [gdgmad/gdgmadevents#7]
Currently the readme contains very less information about the lets build program. We should add a section there mentioning it in detail.

**Comment by AniketSK** [comment]
Was also added in commit https://github.com/gdgmad/gdgmadevents/commit/d61af620772c3d19edea6af9db2ecee53c1053a9 do you feel it could use additional detail?

**Comment by karntrehan** [comment]
Amazing info. Thanks!
