### ISSUE TITLE
Add response JSON structure to ReadMe

### ISSUE THREAD

**Issue by karntrehan** [gdgmad/gdgmadevents#8]
The ReadMe does not contain the sample JSON response. We should add it there.

**Comment by AniketSK** [comment]
This was added in commit https://github.com/gdgmad/gdgmadevents/commit/d61af620772c3d19edea6af9db2ecee53c1053a9 and can be seen in the current README.
If you suggestions on the language of it, additions etc, message in the group or just go ahead and make them.
